[versions]
agp = "8.1.2"
kotlin = "1.9.10"

[plugins]
agp-lib = { id = "com.android.library", version.ref = "agp" }
agp-app = { id = "com.android.application", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
# androidx
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.12.0" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common", version = "2.6.2" }

# google
google-guava = { module = "com.google.guava:guava", version = "31.1-jre" }
google-material = { module = "com.google.android.material:material", version = "1.9.0" }
google-protobuf-java = { module = "com.google.protobuf:protobuf-java", version = "3.23.0" }

# add-ons
bcprov-jdk15on = { module = "org.bouncycastle:bcprov-jdk15on", version = "1.70" }
android-tools-zipflinger = { module = "com.android:zipflinger", version.ref = "agp" }
android-tools-signflinger = { module = "com.android:signflinger", version.ref = "agp" }
android-tools-bundletool = { module = "com.android.tools.build:bundletool", version = "1.15.5" }

# test
junit = { module = "junit:junit", version = "4.13.2" }
androidx-test-junit = { module = "androidx.test.ext:junit", version = "1.1.5" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version = "3.5.1" }
